{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "EmailServiceAPI",
    "description" : "An API with email failover integration.",
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "https://qidbya79aj.execute-api.us-west-2.amazonaws.com/{basePath}",
    "variables" : {
      "basePath" : {
        "default" : "/api"
      }
    }
  } ],
  "paths" : {
    "/email" : {
      "post" : {
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/EmailApiRequest"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "200 response",
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/EmailApiResponse"
                }
              }
            }
          }
        },
        "security" : [ {
          "api_key" : [ ]
        } ],
        "x-amazon-apigateway-request-validator" : "Validate body, query string parameters, and headers",
        "x-amazon-apigateway-integration" : {
          "type" : "aws",
          "credentials" : "${iam_role_arn}",
          "httpMethod" : "PUT",
          "uri" : "arn:aws:apigateway:${region}:sqs:path/${account_id}/${email_sqs_name}",
          "responses" : {
            "default" : {
              "statusCode" : "200"
            }
          },
          "requestParameters" : {
            "integration.request.querystring.MessageBody" : "method.request.body",
            "integration.request.querystring.Action" : "'SendMessage'"
          },
          "passthroughBehavior" : "when_no_match"
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "EmailApiResponse" : {
        "type" : "object",
        "properties" : {
          "Id" : {
            "type" : "string"
          }
        }
      },
      "EmailApiRequest" : {
        "type" : "object",
        "required" : [ "to", "to_name", "from", "from_name", "subject", "body" ],
        "properties" : {
          "to" : {
            "type" : "string"
          },
          "to_name" : {
            "type" : "string"
          },
          "from" : {
            "type" : "string"
          },
          "from_name" : {
            "type" : "string"
          },
          "subject" : {
            "type" : "string"
          },
          "body" : {
            "type" : "string"
          }
        }
      }
    },
    "securitySchemes" : {
      "api_key" : {
        "type" : "apiKey",
        "name" : "x-api-key",
        "in" : "header"
      }
    }
  },
  "x-amazon-apigateway-request-validators" : {
    "Validate body, query string parameters, and headers" : {
      "validateRequestParameters" : true,
      "validateRequestBody" : true
    }
  }
}