name: Deploy Email Service API Gateway

on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

  workflow_dispatch:

jobs:
  deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
            aws-region: us-west-2

        - name: Configure Terraform CLI
          uses: hashicorp/setup-terraform@v1.2.1
          with:
            terraform_version: 0.14.6

        - name: Deploy Terraform Infrastructure
          working-directory: ./infrastructure/deploy
          run: |
            chmod +x deploy.sh
            sh deploy.sh api_gateway
